name: isolates
author: Dart Team <misc@dartlang.org>
version: 3.0.3+8
homepage: https://github.com/dart-lang/isolate
description: Fork of isolates project
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  collection: ^1.15.0
dev_dependencies: 
  pedantic: ^1.11.0
  test: ^1.16.8
